### ISSUE TITLE
Add support for getting tokens from new Test-environment

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/MaskinportenTokenGenerator#3]
### Description

ref.: https://samarbeid.digdir.no/maskinporten/maskinporten/1245

the ver2 environment/issuer is to be turned off Q3 2023 and is replaced by the new test-environment and issuer which is already available.

The MaskinportenTokenGenerator should also be updated with support for the test-environment and issuer, in order to easier test our own client updates.

**Comment by elsand** [comment]
This is possible with

```
set test_token_endpoint="https://test.maskinporten.no/token"
set test_audience="https://test.maskinporten.no/"
```

Leaving open, as this should be the default at some point.

**Comment by acn-dgopa** [comment]
In addition to this configuration, it is required that we also update the code to send code_challenge (PKCE) along with code_challenge_method (Only S256 is supported according to digdir docs).  More info [here](https://docs.digdir.no/docs/idporten/oidc/oidc_func_pkce.html)

**Comment by elsand** [comment]
@acn-dgopa Can you add that as a separate issue?

**Comment by elsand** [comment]
Updated with default support for the "test" endpoints, closing. PKCE support tracked in #4
